### PR TITLE
[BUG] Fix Add method in LayerTable

### PR DESCRIPTION
**Pull request by StudioWEngineers**
The `Add` method in `File3dmLayerTable` does not update the layer `Index` after adding it to the table, so the return value is lost and the original layer object is not anymore consistent with the table.
Not sure if this is the intended behavior or a bug though.

Test has been added.

### CODE REVIEW

**Comment by StudioWEngineers** [comment]
I think I based my branch on https://github.com/mcneel/rhino3dm/tree/luis/delete and not on `mcneel/dev`...

**Comment by fraguada** [comment]
When I test this with adding layers without this fix it works correctly. Can you provide an example where it does not work?

**Comment by StudioWEngineers** [comment]
test fails on `rhino3dm 8.9.0 `

image

**Comment by fraguada** [comment]
I'm checking against the code in the dev or luis/delete branches and this works without any changes

**Comment by StudioWEngineers** [comment]
I am probably missing something basic, but it seems to me that this test is failing in the current `mcneel/dev` branch, updated a while ago  after https://github.com/mcneel/rhino3dm/pull/657.

can you please have look here?
https://github.com/StudioWEngineers/rhino3dm/pull/1

image

**Comment by fraguada** [comment]
It makes sense that it fails. You are looking at the layer prior to it being added to the model. If you retrieve the layer from the model, you will see it has the right index:

```python
    def test_Add(self) -> None:
        """Test for the Add method of File3dmLayerTable.
        """
        file3dm = rhino3dm.File3dm()
        file3dm.ApplicationName = 'python'
        file3dm.ApplicationDetails = 'rhino3dm-tests-Add'
        file3dm.ApplicationUrl = 'https://rhino3d.com'

        # create layer
        layer_index_0 = rhino3dm.Layer()
        # add the layer to the table the update the index accordingly
        index = file3dm.Layers.Add(layer_index_0)

        l0 = file3dm.Layers.FindIndex(index)

        self.assertEqual(l0.Index, 0)
```

**Comment by StudioWEngineers** [comment]
I would have expected the original layer kept up to date.

Anyway, no it seems clear to me and I really appreciate the time you spent to provide feedback.

Summarizing our discussion, a Layer can be modified only before adding it to the table. If a Layer is retrieved from the table then it is const-qualified. It could be maybe a good idea to add a short explanation in the docs, since it is not obvious.

**Pull request closed without merging**
