### PR TITLE
implements BND_Transform.ToFloatArray() to return the transformation matrix

### PR DESCRIPTION
**Pull request by lfertig**
Adresses #128 / RH3DM-56.

There is currently no way to get the actual transformation data from the BND_Transform class (the corresponding function "ToFloatArray()" in bnd_xform.h, line 61, is not implemented). This makes it impossible to properly place instance references when reading from the 3dm file.

The PR implements ToFloatArray() by returning the transformation matrix through pybind11:array_t as a numpy.ndarray.

### CODE REVIEW

**Comment by sbaer** [comment]
Thanks for the PR. In order to complete this I will need to add a bool parameter to determine if the array should be rowDominant as this will match the RhinoCommon function defined at
https://developer.rhino3d.com/api/RhinoCommon/html/M_Rhino_Geometry_Transform_ToFloatArray.htm

Would a tuple of 16 values work for you? I would rather not pull in all of the numpy dependencies if this is not necessary.

**Comment by lfertig** [comment]
I thought it would be useful to have the array as a numpy array to be able to directly be able to use numpys matrix math tools (there's also an option to the constructor to pass it as either a c- or f-style array). I see the point though of not making everything dependent on another library just for one function. 

Would you want to return just one tuple of 16 consecutive values or rather a nested tuple 4x4?

**Comment by sbaer** [comment]
A flat tuple of 16 values would be my preference as this matches our .NET equivalent function.

**Comment by lfertig** [comment]
ok, will do so

**Comment by sbaer** [comment]
a bunch of extra files got added to the PR

**Pull request closed without merging**
